In [2]:
import numpy as np

In [68]:
## 1
def col_power_in_list(vec, increasing = False):
    l = len(vec)
    mt = np.zeros(shape=(l,l), dtype = np.int8)
    for j in range(l):
        for k in range(l):
            mt[j,k]=vec[j]**k
    return mt

b = np.array(range(1,6))

print('The vector to be passed is as below ..')
print('-'*40)
print(b)

print('\n')
print('The result matrix is as below ..')
print('-'*35)
print(col_power_in_list(b))

The vector to be passed is as below ..
----------------------------------------
[1 2 3 4 5]


The result matrix is as below ..
-----------------------------------
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64   0]
 [  1   5  25 125 113]]


In [71]:
## 2

def moving_avg(in_vec, window_size):
    n = len(in_vec)
    num_avg = (n - window_size + 1)
    avg_vec = []
    
    for i in range(num_avg):
        avg_vec.append(sum(in_vec[i:i+window_size])/window_size)
        
    return avg_vec

print('The test vector to be passed is as below ..')
print('-'*45)
test_vec = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(test_vec)

print('\n')
print('The result moving average vector is as below ..')
print('-'*50)
print(moving_avg(test_vec, 3))

The test vector to be passed is as below ..
---------------------------------------------
[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]


The result moving average vector is as below ..
--------------------------------------------------
[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
